CREATE DATABASE ASSIGNMENT_21010101117

USE ASSIGNMENT_21010101117
CREATE TABLE MST_CITY

( CITYID INT NOT NULL PRIMARY KEY,
	CITYNAME VARCHAR(250) NOT NULL,
	PINCODE VARCHAR(6),
	STATEID INT FOREIGN KEY
	REFERENCES MST_STATE(STATEID),
	CITYREMARK VARCHAR(500)
)

INSERT INTO MST_CITY VALUES (1,'RAJKOT',360005,1,'CLEAN'),(2,'AHMEDABAD',360001,1,'GOOD'),(3,'JAIPUR',361001,2,'AVG'),(4,'PANCHMANDI',365005,3,'CLEAN'),(5,'MORBI',360015,1,'CLEAN')

CREATE TABLE MST_STATE(
STATEID INT PRIMARY KEY,
STATENAME VARCHAR(100)
)

INSERT INTO MST_STATE VALUES(1,'GUJRAT'),(2,'RAJSTHAN'),(3,'M.P.'),(4,'U.P.'),(5,'KARNATAK')


--PR_MST_CITY_SELECTALL
CREATE PROC PR_MST_CITY_SELECTALL
AS
BEGIN
SELECT MST_CITY.CityID,MST_CITY.CityName,MST_CITY.Pincode,MST_CITY.CityRemark,MST_STATE.StateID,MST_STATE.StateName
FROM MST_CITY
INNER JOIN MST_STATE
ON MST_CITY.STATEID=MST_STATE.STATEID
END

--PR_MST_CITY_INSERT 6,'ATKOT',366666,1,'MAST'
CREATE PROC PR_MST_CITY_INSERT
@CITYID			INT,
@CITYNAME		VARCHAR(250),
@PINCODE		VARCHAR(6),
@STATEID		INT,
@CITYREMARK		VARCHAR(500)
AS
BEGIN
INSERT INTO MST_CITY
(	CITYID,
	CITYNAME,	
	PINCODE,
	STATEID,	
	CITYREMARK)
VALUES(
	@CITYID,	
	@CITYNAME,	
	@PINCODE,	
	@STATEID,	
	@CITYREMARK
)
END	

--PR_MST_CITY_UPDATE 6,'LILAPUR',360055,1,'BEUTIFUL'
CREATE PROC PR_MST_CITY_UPDATE
@CITYID			INT,
@CITYNAME		VARCHAR(250),
@PINCODE		VARCHAR(6),
@STATEID		INT,
@CITYREMARK		VARCHAR(500)
AS
BEGIN
UPDATE MST_CITY SET
CITYNAME=@CITYNAME,
PINCODE=@PINCODE,
STATEID=@STATEID,	
CITYREMARK=@CITYREMARK
WHERE CITYID=@CITYID
END

--PR_MST_CITY_DELETE 6
CREATE PROC PR_MST_CITY_DELETE
@CITYID INT
AS
BEGIN
DELETE FROM MST_CITY
WHERE CITYID=@CITYID
END

--PR_MST_CITY_SELECT_BY_PK 5
CREATE PROC PR_MST_CITY_SELECT_BY_PK
@CITYID INT
AS
BEGIN
SELECT *
FROM MST_CITY
WHERE CITYID=@CITYID
END

--PR_MST_CITY_SelectByPincodeStartWith360
CREATE PROC PR_MST_CITY_SelectByPincodeStartWith360
AS
BEGIN
SELECT *
FROM MST_CITY
WHERE PINCODE LIKE '360%'
END

--PR_MST_CITY_SelectByCityNamePincode 'RAJKOT',360005
CREATE PROC PR_MST_CITY_SelectByCityNamePincode
@CITYNAME VARCHAR(250),
@PINCODE  VARCHAR(6)
AS
BEGIN
SELECT *
FROM MST_CITY
WHERE CITYNAME=@CITYNAME AND PINCODE=@PINCODE
END

--PR_MST_CITY_SelectByCityRemarks 'CLEAN'
CREATE PROC PR_MST_CITY_SelectByCityRemarks
@CITYREMARK VARCHAR(500)
AS
BEGIN
SELECT *
FROM MST_CITY
WHERE CITYREMARK=@CITYREMARK
END

--PR_MST_CITY_SelectByStateID 1
CREATE PROC PR_MST_CITY_SelectByStateID
@STATEID INT
AS
BEGIN
SELECT *
FROM MST_CITY
WHERE STATEID=@STATEID
END

--PR_MST_CITY_SelectByStateIDCityID 1,1
CREATE PROC PR_MST_CITY_SelectByStateIDCityID
@STATEID	INT,
@CITYID		INT
AS
BEGIN
SELECT *
FROM MST_CITY
WHERE STATEID=@STATEID AND CITYID=@CITYID
END